defaults:
  - agents: bc_agent

method: ''
agent_name: bc
dynamics_model_name: ''
log_dir: logs/stacking/

seed: 42
action_data_ratio: 10
train_data_path: environments/dataset/data/stacking/train_files.pkl
eval_data_path: environments/dataset/data/stacking/eval_files.pkl

# insert wandb here
wandb:
  entity: bijianxin292430887
  project: d3il

group: stacking_${agent_name}

hydra:
  run:
    dir: ${log_dir}/runs/${agent_name}
  sweep:
    dir: ${log_dir}/sweeps/${agent_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

backbone: 'mlp'
# Action Decoder Network
hidden_dims: [256]
# FSQ
fsq_levels: [6,6,6,6]
fsq_latent_dim: 4
# AE/VQ-VAE
ae_latent_dim: 4
codebook_size: 256
#VAE
vae_latent_dim: 4
kl_factor: 0.0001
#Koopman
kpm_latent_dim: 256
target_k: -1
kpm_latent_dim_nl: 4
#Cotrain
action_loss_factor: 0.01
# Training
train_batch_size: 256
val_batch_size: 256
num_workers: 4
device: 'cuda'
epoch: 400
eval_every_n_epochs: 5
decoder_eval_every_n_epochs: 5
scale_data: False
# use original dataset to normalize data
scale_set: True
# Environment
obs_dim: 20 # robot_feature + obj_feature * num_obj
action_dim: 8
max_len_data: 1000
window_size: 5

obs_mask_dim: [3,7]
robot_state_dim: 8

shape_meta: &shape_meta
  robot_feature:
    shape: [8] # robot_des_j_pos, robot_gripper
  obj_feature:
    shape: [4] # box_pos, box_euler_angle_z

# Dataset
trainset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  action_data_ratio: ${action_data_ratio}
  obs_data_ratio: 25
  seed: ${seed}
  only_label_data: False

finetuneset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  action_data_ratio: ${action_data_ratio}
  obs_data_ratio: 25
  seed: ${seed}
  only_label_data: True

valset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${eval_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  action_data_ratio: 100
  only_label_data: True
  seed: ${seed}

totalset:
  _target_: environments.dataset.stacking_dataset.Stacking_Dataset
  data_directory: ${train_data_path}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  max_len_data: ${max_len_data}
  window_size: ${window_size}
  action_data_ratio: 100
  seed: ${seed}

# Simulation
simulation:
  _target_: simulation.stacking_sim1.Stacking_Sim
  seed: ${seed}
  device: ${device}
  render: False
  n_cores: 4
  n_contexts: 20
  n_trajectories_per_context: 3
  max_steps_per_episode: 400