_target_: agents.idm_vae_cotrain.IDM_Cotrain_Agent
_recursive_: false

model:
  _target_: agents.idm_vae_cotrain.IDM_Cotrain_Policy
  _recursive_: false
  device: ${device}
  idm_model:
    _target_: agents.models.idm.idm_model.VariationalAutoEncoder
    input_dim: ${obs_dim}
    hidden_dims: ${hidden_dims}
    latent_dim: ${vae_latent_dim}
    action_dim: ${action_dim}
    mask_dim: ${obs_mask_dim}
    backbone: ${backbone}

kl_factor: ${kl_factor}
obs_mask_dim: ${obs_mask_dim}
trainset: ${trainset}
valset: ${valset}
totalset: ${totalset}

optimization:
  _target_: torch.optim.AdamW
  lr: 3e-4
  weight_decay: 0.01

train_batch_size: ${train_batch_size}
val_batch_size: ${val_batch_size}
num_workers: ${num_workers}
epoch: ${epoch}
device: ${device}
scale_data: False
eval_every_n_epochs: ${decoder_eval_every_n_epochs}
action_loss_factor: ${action_loss_factor}
