_target_: agents.idm_agent.IDM_Agent
_recursive_: false

device: ${device}
trainset: ${trainset}
obs_encoder:
  _target_: torch.nn.Identity
  output_dim: ${obs_dim}

### same as idm_latent_policy.yaml
latent_policy:
  _target_: agents.idm_latent_policy.IDM_Latent_Policy_Agent
  _recursive_: false

  model:
    _target_: agents.idm_latent_policy.IDM_Latent_Policy
    _recursive_: false

    visual_input: False
    device: ${device}

    input_dim: ${obs_dim}

    diffusion_opt:
      beta_max: 0.3
      interval: 50
      device: ${device}
      ema: 0.9

    obs_encoder:
      _target_: torch.nn.Identity
      output_dim: ${obs_dim}

  trainset: ${trainset}
  valset: ${valset}


  optimization:
    _target_: torch.optim.Adam
    lr: 1e-4
    weight_decay: 0

  train_batch_size: ${train_batch_size}
  val_batch_size: ${val_batch_size}
  num_workers: ${num_workers}
  epoch: ${epoch}
  device: ${device}
  scale_data: False
  eval_every_n_epochs: ${eval_every_n_epochs}


###load action decoder
action_decoder:
  _target_: agents.idm_decoder.IDM_Decoder_Agent
  _recursive_: false

  model:
    _target_: agents.idm_decoder.IDM_Decoder_Policy
    _recursive_: false

    visual_input: False
    device: ${device}

    obs_encoder:
      _target_: torch.nn.Identity
      output_dim: ${obs_dim}

    action_decoder:
      _target_: agents.models.idm.sequence.LSTMNetwork
      input_dim: ${ae_latent_dim}
      cond_dim: ${obs_dim}
      hidden_dims: ${hidden_dims}
      output_dim: ${action_dim}

    idm_ckpt_path: /${log_dir}runs/${dynamics_model_name}/

    ###load idm dynamics agent
    idm_dynamics:
      _target_: agents.idm_dynamics.IDM_Dynamics_Agent
      _recursive_: false

      model:
        _target_: agents.idm_dynamics.IDM_Dynamics
        _recursive_: false

        visual_input: False
        device: ${device}

        model:
          _target_: agents.models.idm.idm_model.AutoEncoder
          latent_dim: ${ae_latent_dim}
          input_dim: ${obs_dim}

        obs_encoder:
          _target_: torch.nn.Identity
          output_dim: ${obs_dim}

      obs_mask_dim: ${obs_mask_dim}
      trainset: ${trainset}
      valset: ${valset}


      optimization:
        _target_: torch.optim.Adam
        lr: 1e-3
        weight_decay: 0

      train_batch_size: ${train_batch_size}
      val_batch_size: ${val_batch_size}
      num_workers: ${num_workers}
      epoch: ${epoch}
      device: ${device}
      scale_data: False
      eval_every_n_epochs: ${eval_every_n_epochs}


  trainset: ${decoder_trainset}
  valset: ${valset}
  totalset: ${trainset}
  obs_mask_dim: ${obs_mask_dim}
  optimization:
    _target_: torch.optim.Adam
    lr: 1e-3
    weight_decay: 0

  train_batch_size: ${train_batch_size}
  val_batch_size: ${val_batch_size}
  num_workers: ${num_workers}
  epoch: ${epoch}
  device: ${device}
  scale_data: False
  eval_every_n_epochs: ${eval_every_n_epochs}
